var products = [
    // {
    //     name: '',
    //     zone: [],
    //     colors: [],
    //     cycle: [],
    //     sunshade: [],
    //     yardheight: [],
    //     planttime: [],
    //     bloomtime: [],
    //     solutions: [],
    //     doinggood: []
    // }

    {
        name: 'No Mow Lawn Grass Seed',
        zone: [4, 5, 6, 7],
        colors: [8],
        cycle: [2],
        sunshade: [1,2],
        yardheight: [2,3,4,5],
        planttime: [2,8],
        bloomtime: [3,4],
        solutions: [0,4],
        doinggood: []
    },
    {
        name: 'Microclover Seed (Pelleted)',
        zone: [3, 4, 5, 6, 7, 8],
        colors: [8],
        cycle: [2],
        sunshade: [1,2],
        yardheight: [2,3,4,5],
        planttime: [8],
        bloomtime: [3,4],
        solutions: [0,4],
        doinggood: []
    },
    {
        name: 'No Mow Lawn & Microclover Seed Mix',
        zone: [4, 5, 6, 7],
        colors: [8],
        cycle: [2],
        sunshade: [1,2],
        yardheight: [2,3,4,5],
        planttime: [2,3,4,5,6,7,8],
        bloomtime: [],
        solutions: [0,4],
        doinggood: []
    },
    // {
    //     name: 'Low Work and Water Dwarf Fescue',
    //     zone: [5, 6, 7, 8, 9, 10],
    //     colors: [8],
    //     cycle: [2],
    //     sunshade: [1,2],
    //     yardheight: [2,3,4,5],
    //     planttime: [],
    //     bloomtime: [2,3,4,5],
    //     solutions: [0,4],
    //     doinggood: []
    // },
    // {
    //     name: 'Pollinator Cover Crop Seed Mix',
    //     zone: [4, 5, 6, 7, 8],
    //     colors: [8,9,6,1,5],
    //     cycle: [2,3],
    //     sunshade: [1],
    //     yardheight: [5],
    //     planttime: [7,8],
    //     bloomtime: [1,2,3,4,5,6],
    //     solutions: [0,7],
    //     doinggood: [1]
    // },
    {
        name: 'No Mow Flowering Lawn',
        zone: [4, 5, 6, 7],
        colors: [8],
        cycle: [2],
        sunshade: [1,2],
        yardheight: [2,3,4,5],
        planttime: [2,8],
        bloomtime: [2,3,4,5],
        solutions: [0,4],
        doinggood: [1,2]
    },
    {
        name: 'Alternative Lawn Wildflower Seed Mix',
        zone: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        colors: [9,5,1,8,6,7],
        cycle: [4],
        sunshade: [1,2],
        yardheight: [3,4,5],
        planttime: [],
        bloomtime: [2,5,8],
        solutions: [0],
        doinggood: [1,2,4,3]
    },
    // {
    //     name: 'Wildflower Yard Annual Bold Color Mix',
    //     zone: [3, 4, 5, 6, 7, 8, 9, 10],
    //     colors: [4,7,1,3,6,9],
    //     cycle: [1],
    //     sunshade: [1,2],
    //     yardheight: [3,4,5],
    //     planttime: [],
    //     bloomtime: [2,5,8],
    //     solutions: [0],
    //     doinggood: [1,2,4,3]
    // },
    {
        name: 'Wildflower Yard Annual Vivid Variety',
        zone: [3, 4, 5, 6, 7, 8, 9, 10],
        colors: [1,5,4,9,6,7,3],
        cycle: [1],
        sunshade: [1,2],
        yardheight: [3,4,5],
        planttime: [],
        bloomtime: [],
        solutions: [0,7],
        doinggood: [0,1,2,3,4]
    },
    // {
    //     name: 'Picket Fence Wildflower Seed Mix',
    //     zone: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    //     colors: [5,9,1,4,7,2,6],
    //     cycle: [1],
    //     sunshade: [1,2],
    //     yardheight: [4,5],
    //     planttime: [],
    //     bloomtime: [],
    //     solutions: [0],
    //     doinggood: [1,2,4,3]
    // },
    {
        name: 'Mini Meadows Wildflower Seed Mix',
        zone: [3, 4, 5, 6, 7, 8],
        colors: [5,6,2,7,9,1,4],
        cycle: [4],
        sunshade: [1,2],
        yardheight: [5],
        planttime: [],
        bloomtime: [4,5,6,7,8,9],
        solutions: [0,7],
        doinggood: [1,2,4,3]
    },
    // {
    //     name: 'Perennial Beauty Wildflower Seed Mix',
    //     zone: [1, 2, 3, 4, 5, 6, 7, 8],
    //     colors: [1,2,3,4,5,6,7],
    //     cycle: [2,3],
    //     sunshade: [1,2],
    //     yardheight: [4,5],
    //     planttime: [],
    //     bloomtime: [],
    //     solutions: [0],
    //     doinggood: [0,1,2,3,4]
    // },
    // {
    //     name: 'Amazing Grace Creeping Phlox',
    //     zone: [2, 3, 4, 5, 6, 7, 8, 9],
    //     colors: [9],
    //     cycle: [2],
    //     sunshade: [1],
    //     yardheight: [2,3,4,5],
    //     planttime: [2,3,4,5,8],
    //     bloomtime: [2,3],
    //     solutions: [0,1],
    //     doinggood: [1,2]
    // },
    // {
    //     name: 'Orchid Frost Lamium',
    //     zone: [3, 4, 5, 6, 7, 8],
    //     colors: [5],
    //     cycle: [2],
    //     sunshade: [2,3],
    //     yardheight: [2,3,4,5],
    //     planttime: [2,3,4,5,8],
    //     bloomtime: [3,4,5,6,7,8],
    //     solutions: [0,1,3],
    //     doinggood: [3]
    // },
    {
        name: 'Jacob Cline Bee Balm',
        zone: [4, 5, 6, 7, 8, 9],
        colors: [4],
        cycle: [2],
        sunshade: [1,2],
        yardheight: [4,5],
        planttime: [2,3,4,5,8],
        bloomtime: [],
        solutions: [0,1,2],
        doinggood: [1,2,5,6,3,4]
    },
    {
        name: 'Phenomenal Lavender',
        zone: [5, 6, 7, 8, 9],
        colors: [6],
        cycle: [2],
        sunshade: [1],
        yardheight: [4,5],
        planttime: [2,3,4,5,8],
        bloomtime: [5,6,7],
        solutions: [0,1,2],
        doinggood: [1,2,4]
    },
    {
        name: 'Joe Pye Weed',
        zone: [4, 5, 6, 7, 8],
        colors: [5],
        cycle: [2],
        sunshade: [1],
        yardheight: [5],
        planttime: [2,3,4,5,8],
        bloomtime: [6,7,8],
        solutions: [0,1,2],
        doinggood: [1,2,0,3,4]
    },
    {
        name: 'Common Milkweed',
        zone: [3, 4, 5, 6, 7, 8, 9],
        colors: [5],
        cycle: [2],
        sunshade: [1],
        yardheight: [4,5],
        planttime: [2,3,4,5,8],
        bloomtime: [5,6],
        solutions: [0,1,2],
        doinggood: [1,2,0]
    },
    {
        name: 'Elijah Blue Fescue',
        zone: [4, 5, 6, 7, 8, 9],
        colors: [8],
        cycle: [2],
        sunshade: [1],
        yardheight: [3,4,5],
        planttime: [2,3,4,5,8],
        bloomtime: [],
        solutions: [0,1],
        doinggood: []
    },
    {
        name: 'Pennsylvania Sedge Grass',
        zone: [3, 4, 5, 6, 7, 8],
        colors: [8],
        cycle: [2],
        sunshade: [2,3],
        yardheight: [3,4,5],
        planttime: [2,3,4,5,8],
        bloomtime: [],
        solutions: [0,1],
        doinggood: [0]
    },
    {
        name: 'Karl Forester Feather Reed Grass',
        zone: [5, 6, 7, 8, 9],
        colors: [8],
        cycle: [2],
        sunshade: [1,2],
        yardheight: [4,5],
        planttime: [2,3,4,5,8],
        bloomtime: [],
        solutions: [0,7,1,2],
        doinggood: [0]
    },
    {
        name: 'Prairie Blues Little Bluestem',
        zone: [3, 4, 5, 6, 7, 8, 9],
        colors: [7,8],
        cycle: [2],
        sunshade: [1],
        yardheight: [4,5],
        planttime: [2,3,4,5,8],
        bloomtime: [1,2,3,4,5,6,7,8,9,10],
        solutions: [0,1],
        doinggood: [0]
    },
    {
        name: 'Cloud Nine Tall Switchgrass / Northwind Switchgrass',
        zone: [4, 5, 6, 7, 8, 9],
        colors: [8],
        cycle: [2],
        sunshade: [1,2],
        yardheight: [4,5],
        planttime: [2,3,4,5],
        bloomtime: [1,2,3,4,5,6,7,8,9,10],
        solutions: [0,7,1],
        doinggood: [0]
    },
    {
        name: 'Blackhawks Big Bluestem Grass',
        zone: [3, 4, 5, 6, 7, 8, 9],
        colors: [6],
        cycle: [2],
        sunshade: [1],
        yardheight: [4,5],
        planttime: [2,3,4,5,8],
        bloomtime: [6],
        solutions: [0,7,1],
        doinggood: [0]
    },
    {
        name: 'Pink Cloud Muhly Grass',
        zone: [5, 6, 7, 8, 9],
        colors: [5],
        cycle: [2],
        sunshade: [1],
        yardheight: [4,5],
        planttime: [],
        bloomtime: [7,8,9],
        solutions: [0,1,6],
        doinggood: [0,4]
    },
    {
        name: 'Zinnia Mix',
        zone: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        colors: [10],
        cycle: [1],
        sunshade: [1],
        yardheight: [4,5],
        planttime: [2],
        bloomtime: [5,6,7,8],
        solutions: [0,1],
        doinggood: [1,2,3,4]
    },
    {
        name: 'Purple Coneflower',
        zone: [3, 4, 5, 6, 7, 8],
        colors: [5],
        cycle: [2],
        sunshade: [2,3],
        yardheight: [4,5],
        planttime: [],
        bloomtime: [5],
        solutions: [0,1],
        doinggood: [1,2,0,4]
    },
    {
        name: 'Autumn Beauty Sunflower Mix',
        zone: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        colors: [1,2,3,4],
        cycle: [1],
        sunshade: [1,2],
        yardheight: [4,5],
        planttime: [9,10],
        bloomtime: [5],
        solutions: [0,7,1],
        doinggood: [1,2,0,4]
    },
    {
        name: 'Black Eyed Susan',
        zone: [3, 4, 5, 6, 7, 8, 9],
        colors: [1],
        cycle: [2],
        sunshade: [1,2],
        yardheight: [4,5],
        planttime: [2,3,4,5,8],
        bloomtime: [5,6,7],
        solutions: [0,1,2],
        doinggood: [1,2,0,3,4]
    },
    {
        name: 'Cosmos',
        zone: [2, 3, 4, 5, 6, 7, 8, 9, 10],
        colors: [4,5,9],
        cycle: [1],
        sunshade: [1,2],
        yardheight: [5],
        planttime: [],
        bloomtime: [5,6,7,8],
        solutions: [0,7],
        doinggood: [1,2,3,4]
    },
    // {
    //     name: 'Bouquets for Day',
    //     zone: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    //     colors: [10],
    //     cycle: [4],
    //     sunshade: [1,2],
    //     yardheight: [5],
    //     planttime: [],
    //     bloomtime: [3,4,5,6,7,8,9],
    //     solutions: [0,7],
    //     doinggood: [1,2,4]
    // },
    // {
    //     name: 'Monarch Mix',
    //     zone: [3, 4, 5, 6, 7, 8, 9, 10],
    //     colors: [10],
    //     cycle: [4],
    //     sunshade: [1,2],
    //     yardheight: [5],
    //     planttime: [],
    //     bloomtime: [2,3,4,5,6,7,8],
    //     solutions: [0,7],
    //     doinggood: [1,2,0,3,4]
    // },


];
